
CREATE TABLE public.mofs (
    mof_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mof_name TEXT,
    central_metal_atom TEXT,
    organic_ligand TEXT,
    functional_group TEXT
);

CREATE TABLE public.drugs (
    drug_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drug_name TEXT NOT NULL,
    smiles_string TEXT,
    morgan_fp_bit148 BOOLEAN,
    morgan_fp_bit223 BOOLEAN,
    morgan_fp_bit657 BOOLEAN
);

CREATE TABLE public.drug_loading_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    central_metal_atom TEXT,
    organic_ligand TEXT,
    bit148 BOOLEAN,
    bit223 BOOLEAN,
    bit657 BOOLEAN,
    predicted_loading_capacity DOUBLE PRECISION,
    prediction_date TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE public.cytotoxicity_predictions (
    prediction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    central_metal_atom TEXT,
    organic_ligand TEXT,
    concentration DOUBLE PRECISION,
    size DOUBLE PRECISION,
    zeta_potential DOUBLE PRECISION,
    exposure_time DOUBLE PRECISION,
    cell_type TEXT,
    predicted_cell_viability DOUBLE PRECISION,
    prediction_date TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.mofs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drugs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.drug_loading_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cytotoxicity_predictions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "public read mofs" ON public.mofs FOR SELECT USING (true);
CREATE POLICY "public read drugs" ON public.drugs FOR SELECT USING (true);

CREATE POLICY "public read dl preds" ON public.drug_loading_predictions FOR SELECT USING (true);
CREATE POLICY "public insert dl preds" ON public.drug_loading_predictions FOR INSERT WITH CHECK (true);

CREATE POLICY "public read cyto preds" ON public.cytotoxicity_predictions FOR SELECT USING (true);
CREATE POLICY "public insert cyto preds" ON public.cytotoxicity_predictions FOR INSERT WITH CHECK (true);
